language: go
go:
  - "1.10"

matrix:
  include:
    - dist: precise
      sudo: required
      env: PYTHON_VERSION=2
    - dist: trusty
      sudo: required
      env: PYTHON_VERSION=3
    - dist: trusty
      sudo: required
      env: PYTHON_VERSION=2

addons:
  apt:
    update: true
    packages:
      - build-essential

script:
  - go test . -v